### ISSUE TITLE
undefined is not an object (evaluating 'clearCacheModuleObj.clearAppCache')

### ISSUE THREAD

**Issue by mahmoudafer** [midas-gufei/react-native-clear-app-cache#2]
Hello,

I installed the package with the command: 

`npm install react-native-clear-app-cache`

and then linked it with 

`react-native link react-native-clear-app-cache`

yet, when i try to clear cache in the app using: 

`clear.clearAppCache();`

but it shows error:  undefined is not an object (evaluating 'clearCacheModuleObj.clearAppCache')

please help,
thanks a lot

**Comment by midas-gufei** [comment]
android ？iOS？

**Comment by midas-gufei** [comment]
Make sure the Android and IOS libraries are linked.

**Comment by mahmoudafer** [comment]
Ok thanks a lot @tombaki :)
